language: go

go:
 - 1.9
addons:
  ssh_known_hosts:
  - 127.0.0.1

before_install:
 - go get -u -v github.com/golang/lint/golint
 - echo "deb http://mirrors.aliyun.com/ubuntu/ precise varnish-3.0" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install sshpass -y
 - sudo apt-get install dnsmasq -y
 - sudo apt-get install sshpass -y
 - echo "root:ssh" | sudo chpasswd
 - sshpass -p 'ssh' ssh -fN -D 9099 root@127.0.0.1
 - sudo apt-get install openssl -y
 - wget http://www.squid-cache.org/Versions/v3/3.5/squid-3.5.27.tar.gz
 - tar -xzf squid-3.5.27.tar.gz
 - cd squid-3.5.27
 - sudo ./configure '--enable-ssl' '--with-openssl' '--enable-ssl-crtd'
 - sudo apt-get install make -y
 - sudo make
 - sudo make install
 - sudo touch /usr/local/squid/var/logs/access.log /usr/local/squid/var/logs/cache.log
 - sudo chmod 777 /usr/local/squid/var/logs/access.log /usr/local/squid/var/logs/cache.log
 - sudo /usr/local/squid/sbin/squid -f /home/travis/gopath/src/github.com/balinor2017/fastproxy/.travisfile/squid.conf
 - sudo dnsmasq -p 5300 -S 114.114.114.114
 - curl -v -x http://127.0.0.1:3128 icanhazip.com

script:
  - diff -u <(echo -n) <(sudo gofmt -s -d ./)
  - diff -u <(echo -n) <(sudo go vet ./...)
  - diff -u <(echo -n) <(sudo golint)
  - go test -v ./...