language: go

go:
 - 1.9
 - 1.8
 - 1.7
 - 1.6

before_install:
 - go get -u -v github.com/golang/lint/golint
 - apt-get install sshpass
 - apt-get install dnsmasq
 - apt-get install squid
 - apt-get install sshpass

script:
  - echo "root:ssh" | chpasswd
  - sshpass -p 'ssh' ssh -fN -D 12000 root@127.0.0.1
  - dnsmasq -S 114.114.114.114
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint)
  - go test -v -race ./...