language: go

go:
 - 1.9
addons:
  ssh_known_hosts:
  - 127.0.0.1

before_install:
 - go get -u -v github.com/golang/lint/golint
 - echo "deb http://mirrors.aliyun.com/ubuntu/ precise varnish-3.0" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install sshpass -y
 - sudo apt-get install dnsmasq -y
 - sudo apt-get install sshpass -y
 - echo "root:ssh" | sudo chpasswd
 - sshpass -p 'ssh' ssh -fN -D 9099 root@127.0.0.1
 - sudo apt-get --fix-missing install squid -y
 - sudo squid3 -f /home/travis/gopath/src/github.com/balinor2017/fastproxy/.travisfile/squid.conf
 - curl -v -k http://127.0.0.1:3128
 - curl -v -k https://127.0.0.1:3129

script:
  - diff -u <(echo -n) <(sudo gofmt -s -d ./)
  - diff -u <(echo -n) <(sudo go vet ./...)
  - diff -u <(echo -n) <(sudo golint)
  - go test -v ./...