language: go

go:
 - 1.9
addons:
  ssh_known_hosts:
  - 127.0.0.1

before_install:
 - go get -u -v github.com/golang/lint/golint
 - sudo apt-get update
 - sudo apt-get install sshpass -y
 - sudo apt-get install dnsmasq -y
 - sudo apt-get install sshpass -y
 - sudo apt-get --fix-missing install squid -y
 - echo "root:ssh" | sudo chpasswd
 - sshpass -p 'ssh' ssh -fN -D 12000 root@127.0.0.1
 - sudo mkdir -p /home/travis/gopath/src/github.com/haxii/fastproxy/
 - sudo cp -rf ./ /home/travis/gopath/src/github.com/haxii/fastproxy/
 - sudo echo "" > server.crt
 - sudo echo "" > server.key
 - sudo echo "" > /etc/squid.conf
 - squid

script:
  - diff -u <(echo -n) <(sudo gofmt -s -d ./)
  - diff -u <(echo -n) <(sudo go vet ./...)
  - diff -u <(echo -n) <(sudo golint)
  - go test -v -race ./...